-- ANSWER CODE
SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_OUTS B
LEFT OUTER JOIN ANIMAL_INS AS A ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NOT NULL AND (
    (A.SEX_UPON_INTAKE = "Intact Female" AND B.SEX_UPON_OUTCOME="Spayed Female")
    OR 
    (A.SEX_UPON_INTAKE ="Intact Male" AND B.SEX_UPON_OUTCOME="Neutered Male")
)           
ORDER BY B.ANIMAL_ID;
