-- ANSWER CODE
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A  
INNER JOIN ANIMAL_OUTS B ON B.DATETIME < A.DATETIME AND B.ANIMAL_ID = A.ANIMAL_ID
ORDER BY A.DATETIME ASC;
-- 이때 결과는 보호 시작일이 빠른 순으로 조회해야합니다! (문제를 제대로 읽자)
